import { NextFunction, Request, Response } from "express";
import { check } from "express-validator"
import { validateResults } from "../../utils/handleValidators";

const validatorCreateIncident = [
  check("id_service_paper").exists().isString(),
  check("creation_event_place").exists().isString(),
  check("programmed").exists().isString(),
  check("id_insurance").exists().isString(),
  check("service_cost").exists().isString(),
  check("requester").exists().isString(),
  check("folio").exists().isString(),
  check("date").exists().isString(),
  check("received_call").exists().isString(),
  check("activation_call").exists().isString(),
  check("answer_call").exists().isString(),
  check("arrive_hour").exists().isString(),
  check("contact_hour").exists().isString(),
  check("finished_hour").exists().isString(),
  check("observation").exists().isString(),
  check("id_paramedic").exists().isString(),
  check("departure_time").optional({ nullable: true }).isString(),
  check("on_site").optional({ nullable: true }).isString(),
  check("expedient").optional({ nullable: true }).isString(),
  check("start_transfer").optional({ nullable: true }).isString(),
  check("on_hospital").optional({ nullable: true }).isString(),
  check("wait_Time").optional({ nullable: true }).isString(),
  check("event_type").optional({ nullable: true }).isNumeric(),
  check("kms").optional({ nullable: true }).isString(),
  check("registrationaereosupport").optional({ nullable: true }).isString(),
  check("place_occurrence").optional({ nullable: true }).isArray(),
  check("event_location").optional({ nullable: true }).isString(),
  check("event_between_street_one").optional({ nullable: true }).isString(),
  check("event_between_street_two").optional({ nullable: true }).isString(),
  check("event_neighborhood").optional({ nullable: true }).isString(),
  check("event_township").optional({ nullable: true }).isString(),
  check("patient_name").optional({ nullable: true }).isString(),
  check("patient_year").optional({ nullable: true }).isNumeric(),
  check("patient_weight").optional({ nullable: true }).isNumeric(),
  check("patient_gender").optional({ nullable: true }).isNumeric(),
  check("patient_zip_code").optional({ nullable: true }).isNumeric(),
  check("patient_city").optional({ nullable: true }).isString(),
  check("patient_state").optional({ nullable: true }).isString(),
  check("patient_phone").optional({ nullable: true }).isString(),
  check("patient_address").optional({ nullable: true }).isString(),
  check("patient_occupation").optional({ nullable: true }).isString(),
  check("patient_on_charge").optional({ nullable: true }).isString(),
  check("patient_company").optional({ nullable: true }).isString(),
  check("patient_beneficiary").optional({ nullable: true }).isNumeric(),
  check("crash_type").optional({ nullable: true }).isNumeric(),
  check("crash_with").optional({ nullable: true }).isNumeric(),
  check("crash_against_object").optional({ nullable: true }).isNumeric(),
  check("windshield").optional({ nullable: true }).isNumeric(),
  check("in_car").optional({ nullable: true }).isNumeric(),
  check("seatbelt").optional({ nullable: true }).isNumeric(),
  check("aabm").optional({ nullable: true }).isNumeric(),
  check("fire_gun").optional({ nullable: true }).isString(),
  check("white_gun").optional({ nullable: true }).isString(),
  check("ingestion_poisoning").optional({ nullable: true }).isString(),
  check("inhaletion_poisoning").optional({ nullable: true }).isString(),
  check("explosion").optional({ nullable: true }).isString(),
  check("animalHuman").optional({ nullable: true }).isString(),
  check("fall").optional({ nullable: true }).isNumeric(),
  check("own_size").optional({ nullable: true }).isString(),
  check("approx_height").optional({ nullable: true }).isString(),
  check("electrical_burn").optional({ nullable: true }).isString(),
  check("acid_burn").optional({ nullable: true }).isString(),
  check("leak_burn").optional({ nullable: true }).isString(),
  check("hot_substance_burn").optional({ nullable: true }).isString(),
  check("vapor_gas_burn").optional({ nullable: true }).isString(),
  check("biological_burn").optional({ nullable: true }).isString(),
  check("scq_burn").optional({ nullable: true }).isString(),
  check("clinicalCauses").optional({ nullable: true }).isArray(),
  check("others").optional({ nullable: true }).isString(),
  check("init_date").optional({ nullable: true }).isString(),
  check("init_hour").optional({ nullable: true }).isString(),
  check("symptoms").optional({ nullable: true }).isString(),
  check("signals").optional({ nullable: true }).isString(),
  check("G").optional({ nullable: true }).isString(),
  check("P").optional({ nullable: true }).isString(),
  check("A").optional({ nullable: true }).isString(),
  check("C").optional({ nullable: true }).isString(),
  check("FPP").optional({ nullable: true }).isString(),
  check("FUR").optional({ nullable: true }).isString(),
  check("gestation_week").optional({ nullable: true }).isString(),
  check("membranes").optional({ nullable: true }).isString(),
  check("contractions_init").optional({ nullable: true }).isString(),
  check("frequency").optional({ nullable: true }).isString(),
  check("duration_contractions").optional({ nullable: true }).isString(),
  check("contractions_regions").optional({ nullable: true }).isString(),
  check("newborn_data").optional({ nullable: true }).isNumeric(),
  check("newborn_gender").optional({ nullable: true }).isNumeric(),
  check("newborn_apgar").optional({ nullable: true }).isNumeric(),
  check("postpartum_hours").optional({ nullable: true }).isString(),
  check("postpartum_place").optional({ nullable: true }).isString(),
  check("postpartum_bearing").optional({ nullable: true }).isNumeric(),
  check("heart_rate").optional({ nullable: true }).isNumeric(),
  check("breathing_effort").optional({ nullable: true }).isNumeric(),
  check("irritability").optional({ nullable: true }).isNumeric(),
  check("muscle_tone").optional({ nullable: true }).isNumeric(),
  check("coloration").optional({ nullable: true }).isNumeric(),
  check("consciousness_state").optional({ nullable: true }).isArray(),
  check("airway").optional({ nullable: true }).isArray(),
  check("circulation").optional({ nullable: true }).isArray(),
  check("skin").optional({ nullable: true }).isArray(),
  check("characteristics").optional({ nullable: true }).isArray(),
  check("init_evaluation_event").optional({ nullable: true }).isNumeric(),
  check("init_evaluation_rate").optional({ nullable: true }).isNumeric(),
  check("consciousness_state_person").optional({ nullable: true }).isNumeric(),
  check("consciousness_state_time").optional({ nullable: true }).isNumeric(),
  check("consciousness_state_space").optional({ nullable: true }).isNumeric(),
  check("pupillary_evaluation").optional({ nullable: true }).isNumeric(),
  check("occular_response").optional({ nullable: true }).isString(),
  check("verbal_response").optional({ nullable: true }).isString(),
  check("motor_response").optional({ nullable: true }).isString(),
  check("glasgow_response").optional({ nullable: true }).isString(),
  check("facial_asymmetry").optional({ nullable: true }).isNumeric(),
  check("facial_asymmetry_charge").optional({ nullable: true }).isNumeric(),
  check("lowering_arm").optional({ nullable: true }).isNumeric(),
  check("lowering_arm_charge").optional({ nullable: true }).isNumeric(),
  check("lenguage_state").optional({ nullable: true }).isNumeric(),
  check("cincinnatti_state").optional({ nullable: true }).isNumeric(),
  check("rcp").optional({ nullable: true }).isNumeric(),
  check("airway_second_evaluation").optional({ nullable: true }).isString(),
  check("medicaments").optional({ nullable: true }).isString(),
  check("shocks_j").optional({ nullable: true }).isString(),
  check("qty").optional({ nullable: true }).isString(),
  check("first_hour_vitals").optional({ nullable: true }).isString(),
  check("second_hour_vitals").optional({ nullable: true }).isString(),
  check("third_hour_vitals").optional({ nullable: true }).isString(),
  check("four_hour_vitals").optional({ nullable: true }).isString(),
  check("five_hour_vitals").optional({ nullable: true }).isString(),
  check("first_breathing_frequency_vitals").optional({ nullable: true }).isString(),
  check("second_breathing_frequency_vitals").optional({ nullable: true }).isString(),
  check("third_breathing_frequency_vitals").optional({ nullable: true }).isString(),
  check("four_breathing_frequency_vitals").optional({ nullable: true }).isString(),
  check("five_breathing_frequency_vitals").optional({ nullable: true }).isString(),
  check("first_heart_rate_vitals").optional({ nullable: true }).isString(),
  check("second_heart_rate_vitals").optional({ nullable: true }).isString(),
  check("third_heart_rate_vitals").optional({ nullable: true }).isString(),
  check("four_heart_rate_vitals").optional({ nullable: true }).isString(),
  check("five_heart_rate_vitals").optional({ nullable: true }).isString(),
  check("first_o_saturations_vitals").optional({ nullable: true }).isString(),
  check("second_o_saturations_vitals").optional({ nullable: true }).isString(),
  check("third_o_saturations_vitals").optional({ nullable: true }).isString(),
  check("four_o_saturations_vitals").optional({ nullable: true }).isString(),
  check("five_o_saturations_vitals").optional({ nullable: true }).isString(),
  check("first_one_arterial_tension_vitals").optional({ nullable: true }).isString(),
  check("first_two_arterial_tension_vitals").optional({ nullable: true }).isString(),
  check("second_one_arterial_tension_vitals").optional({ nullable: true }).isString(),
  check("second_two_arterial_tension_vitals").optional({ nullable: true }).isString(),
  check("third_one_arterial_tension_vitals").optional({ nullable: true }).isString(),
  check("third_two_arterial_tension_vitals").optional({ nullable: true }).isString(),
  check("four_one_arterial_tension_vitals").optional({ nullable: true }).isString(),
  check("four_two_arterial_tension_vitals").optional({ nullable: true }).isString(),
  check("five_one_arterial_tension_vitals").optional({ nullable: true }).isString(),
  check("five_two_arterial_tension_vitals").optional({ nullable: true }).isString(),
  check("first_temperature_vitals").optional({ nullable: true }).isString(),
  check("second_temperature_vitals").optional({ nullable: true }).isString(),
  check("third_temperature_vitals").optional({ nullable: true }).isString(),
  check("four_temperature_vitals").optional({ nullable: true }).isString(),
  check("five_temperature_vitals").optional({ nullable: true }).isString(),
  check("first_glucose_vitals").optional({ nullable: true }).isString(),
  check("second_glucose_vitals").optional({ nullable: true }).isString(),
  check("third_glucose_vitals").optional({ nullable: true }).isString(),
  check("four_glucose_vitals").optional({ nullable: true }).isString(),
  check("five_glucose_vitals").optional({ nullable: true }).isString(),
  check("first_first_diuresis_vitals").optional({ nullable: true }).isString(),
  check("second_second_diuresis_vitals").optional({ nullable: true }).isString(),
  check("third_third_diuresis_vitals").optional({ nullable: true }).isString(),
  check("four_four_diuresis_vitals").optional({ nullable: true }).isString(),
  check("five_five_diuresis_vitals").optional({ nullable: true }).isString(),
  check("responsible_nurse").optional({ nullable: true }).isString(),
  check("dx_indications").optional({ nullable: true }).isString(),
  check("medicine_first").optional({ nullable: true }).isString(),
  check("medicine_second").optional({ nullable: true }).isString(),
  check("medicine_third").optional({ nullable: true }).isString(),
  check("medicine_four").optional({ nullable: true }).isString(),
  check("medicine_five").optional({ nullable: true }).isString(),
  check("medicine_six").optional({ nullable: true }).isString(),
  check("medicine_seven").optional({ nullable: true }).isString(),
  check("hour_first").optional({ nullable: true }).isString(),
  check("hour_second").optional({ nullable: true }).isString(),
  check("hour_third").optional({ nullable: true }).isString(),
  check("hour_four").optional({ nullable: true }).isString(),
  check("hour_five").optional({ nullable: true }).isString(),
  check("hour_six").optional({ nullable: true }).isString(),
  check("hour_seven").optional({ nullable: true }).isString(),
  check("dosis_first").optional({ nullable: true }).isString(),
  check("dosis_second").optional({ nullable: true }).isString(),
  check("dosis_third").optional({ nullable: true }).isString(),
  check("dosis_four").optional({ nullable: true }).isString(),
  check("dosis_five").optional({ nullable: true }).isString(),
  check("dosis_six").optional({ nullable: true }).isString(),
  check("dosis_seven").optional({ nullable: true }).isString(),
  check("via_first").optional({ nullable: true }).isString(),
  check("via_second").optional({ nullable: true }).isString(),
  check("via_third").optional({ nullable: true }).isString(),
  check("via_four").optional({ nullable: true }).isString(),
  check("via_five").optional({ nullable: true }).isString(),
  check("via_six").optional({ nullable: true }).isString(),
  check("via_seven").optional({ nullable: true }).isString(),
  check("other").optional({ nullable: true }).isString(),
  check("plan_iv").optional({ nullable: true }).isString(),
  check("city_destiny").optional({ nullable: true }).isString(),
  check("state_destiny").optional({ nullable: true }).isString(),
  check("hospital_destiny").optional({ nullable: true }).isNumeric(),
  check("other_hospital_destiny").optional({ nullable: true }).isString(),
  check("area_destiny").optional({ nullable: true }).isString(),
  check("bed_destiny").optional({ nullable: true }).isString(),
  check("especiality_destiny").optional({ nullable: true }).isString(),
  check("medic_destiny").optional({ nullable: true }).isString(),
  check("nourse_destiny").optional({ nullable: true }).isString(),
  check("family_sign").optional({ nullable: true }).isString(),
  check("medic_sign").optional({ nullable: true }).isString(),
  check("doctor_responsable_name").optional({ nullable: true }).isString(),
  check("patient_responsable_name").optional({ nullable: true }).isString(),
  check("authorize").optional({ nullable: true }).isNumeric(),
  check("familiar_name").optional({ nullable: true }).isString(),
  check("familiar_phone").optional({ nullable: true }).isString(),
  check("familiar_address").optional({ nullable: true }).isString(),
  check("operator").optional({ nullable: true }).isNumeric(),
  check("unit").optional({ nullable: true }).isNumeric(),
  check("tum").optional({ nullable: true }).isString(),
  check("dr").optional({ nullable: true }).isString(),
  check("name_support").optional({ nullable: true }).isString(),
  check("cost_support").optional({ nullable: true }).isString(),
  check("deducible_support").optional({ nullable: true }).isString(),
  check("equipment_used_support").optional({ nullable: true }).isString(),
  check("with_frap").optional({ nullable: true }).isString(),
  check("with_recipe").optional({ nullable: true }).isString(),
  check("with_report").optional({ nullable: true }).isString(),
  check("email_serv_ambulance").optional({ nullable: true }).isString(),
  // check("internal_number").optional().isLength({ min: 1, max: 15 }).isString().custom((value, { req }) => {
  //   if (value != '') {
  //     if (!/^[0-9-AZ-az\()\-))]+$/.test(value)) {
  //       throw new Error('El formato del número de teléfono es incorrecto.');
  //     }
  //   } else {
  //     return true;
  //   }
  //   // Si el campo no existe o está vacío, no arrojará ningún error
  //   return true;
  // }),
  // check("internal_number").optional().isLength({ min: 1, max: 15 }).isString().custom((value, { req }) => {
  //   if (value !== '') {
  //     if (!/^[0-9A-Za-z-]+$/g.test(value)) {
  //       throw new Error('El formato del número de interior es incorrecto.');
  //     }
  //   } else {
  //     return true;
  //   }
  //   // Si el campo no existe o está vacío, no arrojará ningún error
  //   return true;
  // }),


  (req: Request, res: Response, next: NextFunction) => {
    validateResults(req, res, next);
  }
]

const validatorUpdateIncident = [
  check("uuid").isString().isLength({ min: 1, max: 255 }),
  check("departure_time").optional({ nullable: true }).isString(),
  check("on_site").optional({ nullable: true }).isString(),
  check("start_transfer").optional({ nullable: true }).isString(),
  check("on_hospital").optional({ nullable: true }).isString(),
  check("wait_Time").optional({ nullable: true }).isString(),
  check("event_type").optional({ nullable: true }).isNumeric(),
  check("kms").optional({ nullable: true }).isString(),
  check("registrationaereosupport").optional({ nullable: true }).isString(),
  check("place_occurrence").optional({ nullable: true }).isArray(),
  check("event_location").optional({ nullable: true }).isString(),
  check("event_between_street_one").optional({ nullable: true }).isString(),
  check("event_between_street_two").optional({ nullable: true }).isString(),
  check("event_neighborhood").optional({ nullable: true }).isString(),
  check("event_township").optional({ nullable: true }).isString(),
  check("patient_name").optional({ nullable: true }).isString(),
  check("patient_year").optional({ nullable: true }).isNumeric(),
  check("patient_weight").optional({ nullable: true }).isNumeric(),
  check("patient_gender").optional({ nullable: true }).isNumeric(),
  check("patient_zip_code").optional({ nullable: true }).isNumeric(),
  check("patient_city").optional({ nullable: true }).isString(),
  check("patient_state").optional({ nullable: true }).isString(),
  check("patient_phone").optional({ nullable: true }).isString(),
  check("patient_address").optional({ nullable: true }).isString(),
  check("patient_occupation").optional({ nullable: true }).isString(),
  check("patient_on_charge").optional({ nullable: true }).isString(),
  check("patient_company").optional({ nullable: true }).isString(),
  check("patient_beneficiary").optional({ nullable: true }).isNumeric(),
  check("crash_type").optional({ nullable: true }).isNumeric(),
  check("crash_with").optional({ nullable: true }).isNumeric(),
  check("crash_against_object").optional({ nullable: true }).isNumeric(),
  check("windshield").optional({ nullable: true }).isNumeric(),
  check("in_car").optional({ nullable: true }).isNumeric(),
  check("seatbelt").optional({ nullable: true }).isNumeric(),
  check("aabm").optional({ nullable: true }).isNumeric(),
  check("fire_gun").optional({ nullable: true }).isString(),
  check("white_gun").optional({ nullable: true }).isString(),
  check("ingestion_poisoning").optional({ nullable: true }).isString(),
  check("inhaletion_poisoning").optional({ nullable: true }).isString(),
  check("explosion").optional({ nullable: true }).isString(),
  check("animalHuman").optional({ nullable: true }).isString(),
  check("fall").optional({ nullable: true }).isNumeric(),
  check("own_size").optional({ nullable: true }).isString(),
  check("approx_height").optional({ nullable: true }).isString(),
  check("electrical_burn").optional({ nullable: true }).isString(),
  check("acid_burn").optional({ nullable: true }).isString(),
  check("leak_burn").optional({ nullable: true }).isString(),
  check("hot_substance_burn").optional({ nullable: true }).isString(),
  check("vapor_gas_burn").optional({ nullable: true }).isString(),
  check("biological_burn").optional({ nullable: true }).isString(),
  check("scq_burn").optional({ nullable: true }).isString(),
  check("clinicalCauses").optional({ nullable: true }).isArray(),
  check("others").optional({ nullable: true }).isString(),
  check("init_date").optional({ nullable: true }).isString(),
  check("init_hour").optional({ nullable: true }).isString(),
  check("symptoms").optional({ nullable: true }).isString(),
  check("signals").optional({ nullable: true }).isString(),
  check("G").optional({ nullable: true }).isString(),
  check("P").optional({ nullable: true }).isString(),
  check("A").optional({ nullable: true }).isString(),
  check("C").optional({ nullable: true }).isString(),
  check("FPP").optional({ nullable: true }).isString(),
  check("FUR").optional({ nullable: true }).isString(),
  check("gestation_week").optional({ nullable: true }).isString(),
  check("membranes").optional({ nullable: true }).isString(),
  check("contractions_init").optional({ nullable: true }).isString(),
  check("frequency").optional({ nullable: true }).isString(),
  check("duration_contractions").optional({ nullable: true }).isString(),
  check("contractions_regions").optional({ nullable: true }).isString(),
  check("newborn_data").optional({ nullable: true }).isNumeric(),
  check("newborn_gender").optional({ nullable: true }).isNumeric(),
  check("newborn_apgar").optional({ nullable: true }).isNumeric(),
  check("postpartum_hours").optional({ nullable: true }).isString(),
  check("postpartum_place").optional({ nullable: true }).isString(),
  check("postpartum_bearing").optional({ nullable: true }).isNumeric(),
  check("heart_rate").optional({ nullable: true }).isNumeric(),
  check("breathing_effort").optional({ nullable: true }).isNumeric(),
  check("irritability").optional({ nullable: true }).isNumeric(),
  check("muscle_tone").optional({ nullable: true }).isNumeric(),
  check("coloration").optional({ nullable: true }).isNumeric(),
  check("consciousness_state").optional({ nullable: true }).isArray(),
  check("airway").optional({ nullable: true }).isArray(),
  check("circulation").optional({ nullable: true }).isArray(),
  check("skin").optional({ nullable: true }).isArray(),
  check("characteristics").optional({ nullable: true }).isArray(),
  check("init_evaluation_event").optional({ nullable: true }).isNumeric(),
  check("init_evaluation_rate").optional({ nullable: true }).isNumeric(),
  check("consciousness_state_person").optional({ nullable: true }).isNumeric(),
  check("consciousness_state_time").optional({ nullable: true }).isNumeric(),
  check("consciousness_state_space").optional({ nullable: true }).isNumeric(),
  check("pupillary_evaluation").optional({ nullable: true }).isNumeric(),
  check("occular_response").optional({ nullable: true }).isString(),
  check("verbal_response").optional({ nullable: true }).isString(),
  check("motor_response").optional({ nullable: true }).isString(),
  check("glasgow_response").optional({ nullable: true }).isString(),
  check("facial_asymmetry").optional({ nullable: true }).isNumeric(),
  check("facial_asymmetry_charge").optional({ nullable: true }).isNumeric(),
  check("lowering_arm").optional({ nullable: true }).isNumeric(),
  check("lowering_arm_charge").optional({ nullable: true }).isNumeric(),
  check("lenguage_state").optional({ nullable: true }).isNumeric(),
  check("cincinnatti_state").optional({ nullable: true }).isNumeric(),
  check("rcp").optional({ nullable: true }).isNumeric(),
  check("airway_second_evaluation").optional({ nullable: true }).isString(),
  check("medicaments").optional({ nullable: true }).isString(),
  check("shocks_j").optional({ nullable: true }).isString(),
  check("qty").optional({ nullable: true }).isString(),
  check("first_hour_vitals").optional({ nullable: true }).isString(),
  check("second_hour_vitals").optional({ nullable: true }).isString(),
  check("third_hour_vitals").optional({ nullable: true }).isString(),
  check("four_hour_vitals").optional({ nullable: true }).isString(),
  check("five_hour_vitals").optional({ nullable: true }).isString(),
  check("first_breathing_frequency_vitals").optional({ nullable: true }).isString(),
  check("second_breathing_frequency_vitals").optional({ nullable: true }).isString(),
  check("third_breathing_frequency_vitals").optional({ nullable: true }).isString(),
  check("four_breathing_frequency_vitals").optional({ nullable: true }).isString(),
  check("five_breathing_frequency_vitals").optional({ nullable: true }).isString(),
  check("first_heart_rate_vitals").optional({ nullable: true }).isString(),
  check("second_heart_rate_vitals").optional({ nullable: true }).isString(),
  check("third_heart_rate_vitals").optional({ nullable: true }).isString(),
  check("four_heart_rate_vitals").optional({ nullable: true }).isString(),
  check("five_heart_rate_vitals").optional({ nullable: true }).isString(),
  check("first_o_saturations_vitals").optional({ nullable: true }).isString(),
  check("second_o_saturations_vitals").optional({ nullable: true }).isString(),
  check("third_o_saturations_vitals").optional({ nullable: true }).isString(),
  check("four_o_saturations_vitals").optional({ nullable: true }).isString(),
  check("five_o_saturations_vitals").optional({ nullable: true }).isString(),
  check("first_one_arterial_tension_vitals").optional({ nullable: true }).isString(),
  check("first_two_arterial_tension_vitals").optional({ nullable: true }).isString(),
  check("second_one_arterial_tension_vitals").optional({ nullable: true }).isString(),
  check("second_two_arterial_tension_vitals").optional({ nullable: true }).isString(),
  check("third_one_arterial_tension_vitals").optional({ nullable: true }).isString(),
  check("third_two_arterial_tension_vitals").optional({ nullable: true }).isString(),
  check("four_one_arterial_tension_vitals").optional({ nullable: true }).isString(),
  check("four_two_arterial_tension_vitals").optional({ nullable: true }).isString(),
  check("five_one_arterial_tension_vitals").optional({ nullable: true }).isString(),
  check("five_two_arterial_tension_vitals").optional({ nullable: true }).isString(),
  check("first_temperature_vitals").optional({ nullable: true }).isString(),
  check("second_temperature_vitals").optional({ nullable: true }).isString(),
  check("third_temperature_vitals").optional({ nullable: true }).isString(),
  check("four_temperature_vitals").optional({ nullable: true }).isString(),
  check("five_temperature_vitals").optional({ nullable: true }).isString(),
  check("first_glucose_vitals").optional({ nullable: true }).isString(),
  check("second_glucose_vitals").optional({ nullable: true }).isString(),
  check("third_glucose_vitals").optional({ nullable: true }).isString(),
  check("four_glucose_vitals").optional({ nullable: true }).isString(),
  check("five_glucose_vitals").optional({ nullable: true }).isString(),
  check("first_first_diuresis_vitals").optional({ nullable: true }).isString(),
  check("second_second_diuresis_vitals").optional({ nullable: true }).isString(),
  check("third_third_diuresis_vitals").optional({ nullable: true }).isString(),
  check("four_four_diuresis_vitals").optional({ nullable: true }).isString(),
  check("five_five_diuresis_vitals").optional({ nullable: true }).isString(),
  check("responsible_nurse").optional({ nullable: true }).isString(),
  check("dx_indications").optional({ nullable: true }).isString(),
  check("medicine_first").optional({ nullable: true }).isString(),
  check("medicine_second").optional({ nullable: true }).isString(),
  check("medicine_third").optional({ nullable: true }).isString(),
  check("medicine_four").optional({ nullable: true }).isString(),
  check("medicine_five").optional({ nullable: true }).isString(),
  check("medicine_six").optional({ nullable: true }).isString(),
  check("medicine_seven").optional({ nullable: true }).isString(),
  check("hour_first").optional({ nullable: true }).isString(),
  check("hour_second").optional({ nullable: true }).isString(),
  check("hour_third").optional({ nullable: true }).isString(),
  check("hour_four").optional({ nullable: true }).isString(),
  check("hour_five").optional({ nullable: true }).isString(),
  check("hour_six").optional({ nullable: true }).isString(),
  check("hour_seven").optional({ nullable: true }).isString(),
  check("dosis_first").optional({ nullable: true }).isString(),
  check("dosis_second").optional({ nullable: true }).isString(),
  check("dosis_third").optional({ nullable: true }).isString(),
  check("dosis_four").optional({ nullable: true }).isString(),
  check("dosis_five").optional({ nullable: true }).isString(),
  check("dosis_six").optional({ nullable: true }).isString(),
  check("dosis_seven").optional({ nullable: true }).isString(),
  check("via_first").optional({ nullable: true }).isString(),
  check("via_second").optional({ nullable: true }).isString(),
  check("via_third").optional({ nullable: true }).isString(),
  check("via_four").optional({ nullable: true }).isString(),
  check("via_five").optional({ nullable: true }).isString(),
  check("via_six").optional({ nullable: true }).isString(),
  check("via_seven").optional({ nullable: true }).isString(),
  check("other").optional({ nullable: true }).isString(),
  check("plan_iv").optional({ nullable: true }).isString(),
  check("city_destiny").optional({ nullable: true }).isString(),
  check("state_destiny").optional({ nullable: true }).isString(),
  check("hospital_destiny").optional({ nullable: true }).isNumeric(),
  check("other_hospital_destiny").optional({ nullable: true }).isString(),
  check("area_destiny").optional({ nullable: true }).isString(),
  check("bed_destiny").optional({ nullable: true }).isString(),
  check("especiality_destiny").optional({ nullable: true }).isString(),
  check("medic_destiny").optional({ nullable: true }).isString(),
  check("nourse_destiny").optional({ nullable: true }).isString(),
  check("familiar_name").optional({ nullable: true }).isString(),
  check("familiar_phone").optional({ nullable: true }).isString(),
  check("familiar_address").optional({ nullable: true }).isString(),
  check("operator").optional({ nullable: true }).isNumeric(),
  check("unit").optional({ nullable: true }).isNumeric(),
  check("tum").optional({ nullable: true }).isString(),
  check("dr").optional({ nullable: true }).isString(),
  check("updated_by").optional({ nullable: true }).isNumeric(),
  check("initialized").optional({ nullable: true }).isNumeric(),

  (req: Request, res: Response, next: NextFunction) => {
    validateResults(req, res, next);
  }
]

const validatorReadIncident = [
  check("uuid").exists().isNumeric(),

  (req: Request, res: Response, next: NextFunction) => {
    validateResults(req, res, next);
  }
]

const validatorUpdateCoords = [
  check("id_incident").exists().isNumeric(),
  check("lesionCoords").exists().isArray(),
  check("lesionCoordsBurn").exists().isArray(),
  check("lesionCoordsChild").exists().isArray(),

  (req: Request, res: Response, next: NextFunction) => {
    validateResults(req, res, next);
  }
]

export { validatorCreateIncident, validatorUpdateIncident, validatorReadIncident, validatorUpdateCoords }